// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeStay.NotificationService.Data;

#nullable disable

namespace WeStay.NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeStay.NotificationService.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsSent");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WeStay.NotificationService.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Channel");

                    b.HasIndex("Name");

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyTemplate = "<h1>Booking Confirmed</h1><p>Dear {{UserName}},</p><p>Your booking {{BookingCode}} has been confirmed.</p><p>Check-in: {{CheckInDate}}</p><p>Check-out: {{CheckOutDate}}</p>",
                            Channel = "Email",
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(384),
                            Description = "Booking confirmation email",
                            IsActive = true,
                            Language = "en",
                            Name = "BookingConfirmation_Email",
                            SubjectTemplate = "Booking Confirmed - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(385),
                            Variables = "[\"UserName\", \"BookingCode\", \"CheckInDate\", \"CheckOutDate\"]"
                        },
                        new
                        {
                            Id = 2,
                            BodyTemplate = "Your booking {{BookingCode}} is confirmed. Check-in: {{CheckInDate}}",
                            Channel = "SMS",
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(387),
                            Description = "Booking confirmation SMS",
                            IsActive = true,
                            Language = "en",
                            Name = "BookingConfirmation_SMS",
                            SubjectTemplate = "Booking Confirmed",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(387),
                            Variables = "[\"BookingCode\", \"CheckInDate\"]"
                        },
                        new
                        {
                            Id = 3,
                            BodyTemplate = "<h1>Welcome {{UserName}}!</h1><p>Thank you for joining WeStay.</p>",
                            Channel = "Email",
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(389),
                            Description = "Welcome email",
                            IsActive = true,
                            Language = "en",
                            Name = "Welcome_Email",
                            SubjectTemplate = "Welcome to WeStay!",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(389),
                            Variables = "[\"UserName\"]"
                        },
                        new
                        {
                            Id = 4,
                            BodyTemplate = "<p>Click here to reset your password: <a href=\"{{ResetLink}}\">Reset Password</a></p>",
                            Channel = "Email",
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(391),
                            Description = "Password reset email",
                            IsActive = true,
                            Language = "en",
                            Name = "PasswordReset_Email",
                            SubjectTemplate = "Reset Your Password",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(391),
                            Variables = "[\"ResetLink\"]"
                        });
                });

            modelBuilder.Entity("WeStay.NotificationService.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(279),
                            Description = "Booking confirmation notification",
                            IsActive = true,
                            Name = "BookingConfirmation",
                            TemplateBody = "Dear {{UserName}}, your booking {{BookingCode}} has been confirmed.",
                            TemplateSubject = "Booking Confirmation - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(279)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(281),
                            Description = "Booking cancellation notification",
                            IsActive = true,
                            Name = "BookingCancellation",
                            TemplateBody = "Dear {{UserName}}, your booking {{BookingCode}} has been cancelled.",
                            TemplateSubject = "Booking Cancelled - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(282)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(284),
                            Description = "Payment confirmation notification",
                            IsActive = true,
                            Name = "PaymentReceived",
                            TemplateBody = "Dear {{UserName}}, payment for booking {{BookingCode}} has been received.",
                            TemplateSubject = "Payment Received - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(284)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(286),
                            Description = "Payment failure notification",
                            IsActive = true,
                            Name = "PaymentFailed",
                            TemplateBody = "Dear {{UserName}}, payment for booking {{BookingCode}} has failed.",
                            TemplateSubject = "Payment Failed - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(286)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(288),
                            Description = "Review reminder notification",
                            IsActive = true,
                            Name = "ReviewReminder",
                            TemplateBody = "Dear {{UserName}}, how was your stay? Please leave a review.",
                            TemplateSubject = "Review Your Stay - {{BookingCode}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(289)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(291),
                            Description = "Security alert notification",
                            IsActive = true,
                            Name = "SecurityAlert",
                            TemplateBody = "Security alert: {{Message}}",
                            TemplateSubject = "Security Alert - {{Subject}}",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(291)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(293),
                            Description = "Password reset notification",
                            IsActive = true,
                            Name = "PasswordReset",
                            TemplateBody = "Click here to reset your password: {{ResetLink}}",
                            TemplateSubject = "Password Reset Request",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(293)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(295),
                            Description = "Welcome notification",
                            IsActive = true,
                            Name = "Welcome",
                            TemplateBody = "Dear {{UserName}}, welcome to WeStay! Start exploring properties.",
                            TemplateSubject = "Welcome to WeStay!",
                            UpdatedAt = new DateTime(2026, 6, 18, 15, 58, 5, 677, DateTimeKind.Utc).AddTicks(295)
                        });
                });

            modelBuilder.Entity("WeStay.NotificationService.Models.UserNotificationPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BookingNotifications")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("bit");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("bit");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SMSEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SecurityNotifications")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserNotificationPreferences");
                });

            modelBuilder.Entity("WeStay.NotificationService.Models.Notification", b =>
                {
                    b.HasOne("WeStay.NotificationService.Models.NotificationType", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WeStay.NotificationService.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
